version: "2"

run:
  concurrency: 8
  timeout: 30m
  issues-exit-code: 1
  modules-download-mode: readonly


issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  default: none
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - revive
    - goimports
    - gocritic
    - unconvert
    - unparam
  fast: false
